substitutions:
  gpio_actron_power: "GPIO4"
  gpio_i2c_sda: "GPIO10"
  gpio_i2c_scl: "GPIO3"
  dac_output_address: "0x60"

i2c:
  sda: ${gpio_i2c_sda}
  scl: ${gpio_i2c_scl}
  scan: true

output:
  - platform: mcp4725
    id: actron_dac
    address: ${dac_output_address}
  
external_components:
  - source:
      type: git
      url: https://github.com/5k1ppy/actron-ultima-esphome
      ref: main
    components:
      - actron_ultima
    refresh: 0s

actron_ultima:
  id: actron_decoder
  pin: ${gpio_actron_power}

text_sensor:
  - platform: actron_ultima
    actron_ultima_id: actron_decoder
    bit_string:
      name: "Actron Raw Frame"
      id: actron_raw_frame
      
sensor:
  - platform: actron_ultima
    actron_ultima_id: actron_decoder

    setpoint_temp:
      name: "Setpoint Temperature"
      id: setpoint_temp


binary_sensor:
  - platform: actron_ultima
    actron_ultima_id: actron_decoder

    cool:
      name: "Cool"

    heat:
      name: "Heat"

    auto_mode:
      name: "Auto"

    run:
      name: "Run"

    fan_low:
      name: "Fan Low"

    fan_mid:
      name: "Fan Mid"

    fan_high:
      name: "Fan High"

    fan_cont:
      name: "Fan Continuous"

    inside:
      name: "Inside"

    timer:
      name: "Timer"

    zone_1:
      name: "Zone 1"

    zone_2:
      name: "Zone 2"

    zone_3:
      name: "Zone 3"

    zone_4:
      name: "Zone 4"

    zone_5:
      name: "Zone 5"

    zone_6:
      name: "Zone 6"

    zone_7:
      name: "Zone 7"

    zone_8:
      name: "Zone 8"
